### ISSUE TITLE
Colaboração

### ISSUE THREAD

**Issue by ottok92** [marciabeatrizcp/dsTask#1]
Olá, Marcia.
Estou tendo que fazer um scraper do Sucupira para uma disciplina. Gostaria de colaborar com o seu projeto. Devo começar a trabalhar nele semana que vem.
Você gostaria de especificar alguma funcionalidade ou tarefa para eu começar?

Obrigado,
Otto

**Comment by marciabeatrizcp** [comment]
Oi Otto
é um repositório de testes! Mas, agradeço seu interesse. Também estou aprendendo scraping
